name: CI

# Trigger on each push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.3

      - name: Execute test with gradle
        run: ./gradlew test
